<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="WebApp" nsURI="http://www.unex.es/dmss/webapp" nsPrefix="WA">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="WebApp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="only_one_home no_isolated_webpages one_survery_and_one_questionary"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="only_one_home" value="self.webpages->select(w: WebPage | w.oclIsTypeOf(Home))->size()=1"/>
      <details key="no_isolated_webpages" value="self.webpages.links->select(l: Link | l.oclIsTypeOf(Internal)).oclAsType(Internal).target->includesAll(self.webpages->select(w: WebPage | not w.oclIsTypeOf(Home)) )  "/>
      <details key="one_survery_and_one_questionary" value="self.webpages->select(w: WebPage | w.oclIsTypeOf(Questionnary))->size()>=1 and self.webpages->select(w: WebPage | w.oclIsTypeOf(Survey))->size()>=1 "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webpages" lowerBound="1"
        upperBound="-1" eType="#//WebPage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialNetworks" upperBound="-1"
        eType="#//SocialNetwork" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiestions" lowerBound="1"
        upperBound="-1" eType="#//Quiestion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MySqlType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referendecEntity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleQuestion" abstract="true" eSuperTypes="#//Quiestion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//QuestionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualRep" eType="#//VisualRepresentation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QuestionType">
    <eLiterals name="MULTIPLE"/>
    <eLiterals name="SHORT" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="LONG" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageS_Q" abstract="true" eSuperTypes="#//WebPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Survey" eSuperTypes="#//PageS_Q">
    <eStructuralFeatures xsi:type="ecore:EReference" name="noansweredquestion" lowerBound="1"
        upperBound="-1" eType="#//NoAnsweredQuestion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisualRepresentation">
    <eLiterals name="BAR_CHART" value="2"/>
    <eLiterals name="LINEAL_CHART" value="3"/>
    <eLiterals name="PIE_CHART" value="4"/>
    <eLiterals name="TEXTUAL" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Questionnary" eSuperTypes="#//PageS_Q">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answered" lowerBound="1"
        upperBound="-1" eType="#//AnsweredQuestion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebPage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="socialnetwork" upperBound="-1"
        eType="#//SocialNetwork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Home" eSuperTypes="#//WebPage"/>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Details" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//WebPage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CRUD" eSuperTypes="#//WebPage">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="External" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Internal" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//WebPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocialNetwork">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MySqlType">
    <eLiterals name="INTEGER"/>
    <eLiterals name="REAL" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="DATE" value="3"/>
    <eLiterals name="STRING" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoAnsweredQuestion" eSuperTypes="#//SimpleQuestion"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnsweredQuestion" eSuperTypes="#//SimpleQuestion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Answer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Quiestion"/>
  <eClassifiers xsi:type="ecore:EClass" name="GruopOfQuestions" eSuperTypes="#//Quiestion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quiestion" lowerBound="1"
        upperBound="-1" eType="#//Quiestion" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
